global:
  scrape_interval: 15s #by default, scrape targets every 15 seconds
  
  # attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, alertmanager etc)
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s #override the global scrape interval
    static_configs:
      - targets: ['localhost:8080', 'localhost:8081']
        labels:
          group: 'production'

      - targets: ['localhost:8082']
        labels:
          group: 'canary'